# Generated by Django 3.1 on 2022-12-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='memberShipInProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_allocated', models.IntegerField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=255)),
                ('duree_projet', models.IntegerField(default=0, verbose_name='duree estimee')),
                ('etat', models.BooleanField(default=False)),
                ('temps_alouee', models.IntegerField()),
                ('createur', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.etudiant')),
                ('membres', models.ManyToManyField(related_name='les_projets', through='App.memberShipInProject', to='App.Etudiant')),
                ('superviseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.coach')),
            ],
        ),
        migrations.AddField(
            model_name='membershipinproject',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.projet'),
        ),
    ]
